version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwertyuio
      MYSQL_USER: root1
      MYSQL_PASSWORD: paaaas
    ports:
      - "9201:9201"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
